Integrated Stale bot for monitoring open issues & added PR & Issue templates
hyperledger-labs/documentation-template pull request #10
Opened 2023-05-29 15:53 UTC by Neilblaze

### Description

Added a Stale bot for monitoring open issues & also integrated a few PR & Issue templates for contributors. 
/cc: @bobbi28

2023-05-31 21:35 UTC, tkuhrt requested changes
Thanks for your pull request. I provided some feedback. Let's continue to improve this PR so that we can get it merged.

2023-05-31 21:35 UTC, tkuhrt commented on .github/workflows/ISSUE_TEMPLATE/config.yaml
Pretty sure this needs to be named `config.yml`. On another repo, the `yaml` extension did not work in GitHub.

2023-05-31 21:35 UTC, tkuhrt commented on .github/workflows/ISSUE_TEMPLATE/bug-report.yaml
> +labels: [Bug, Needs Triage]
```suggestion
labels: [bug, needs triage]
```
I will need to create the label `needs triage` upon acceptance of PR.

2023-05-31 21:35 UTC, tkuhrt commented on .github/workflows/ISSUE_TEMPLATE/bug-report.yaml
> +        If this matter is security related, please disclose it privately via https://discord.gg/hyperledger
Regarding security related issues, we should probably ask for people to send an email to security@hyperledger.org. There is currently no place to privately report security issues on Discord.
```suggestion
        If this matter is security related, please disclose it privately via security@hyperledger.org
```

2023-05-31 21:35 UTC, tkuhrt commented on .github/workflows/ISSUE_TEMPLATE/enhancement.yaml
> +labels: [feature]
```suggestion
labels: [enhancement]
```

Let's use a label that already exists.

2023-05-31 21:35 UTC, tkuhrt commented on .github/workflows/ISSUE_TEMPLATE/enhancement.yaml
> +description: Provide supporting details for a feature in development
```suggestion
description: Provide supporting details for an enhancement
```

2023-05-31 21:35 UTC, tkuhrt commented on .github/workflows/ISSUE_TEMPLATE/improve_docs.yml
> +labels: [doc]
```suggestion
labels: [documentation]
```

2023-05-31 21:35 UTC, tkuhrt commented on .github/workflows/ISSUE_TEMPLATE/improve_docs.yml
> +        - Search the [open issues](https://github.com/hyperledger-labs/documentation-template/issues) to avoid duplicating the issue.
It would be good to have this same disclaimer in the bug and enhancement templates.

2023-05-31 21:35 UTC, tkuhrt commented on README.md
> +This repos serves as a template for creating documentation for Hyperledger projects. The template utilizes MkDocs (documentation at [mkdocs.org](https://www.mkdocs.org)) and the theme Material for Mk
Since we are making a change here, probably should fix another grammar issue.
```suggestion
This repository serves as a template for creating documentation for Hyperledger projects. The template utilizes MkDocs (documentation at [mkdocs.org](https://www.mkdocs.org)) and the theme Material for MkDocs (documentation at [Material for MkDocs](https://squidfunk.github.io/mkdocs-material/)). Material adds a number of extra features to MkDocs, and Hyperledger repositories can take advantage of the theme's [Insiders](https://squidfunk.github.io/mkdocs-material/insiders/) capabilities.
```

2023-05-31 21:35 UTC, tkuhrt commented on .github/workflows/PULL_REQUEST_TEMPLATE.md
Wonder if we should use H1 headers (i.e., `#`) instead of H4 headers (i.e., `####`) throughout this page.

2023-05-31 21:35 UTC, tkuhrt commented on .github/workflows/stale.yml
What labels will we need to create for this?

Are the `daysUntilStale` and `daysUntilClose` typical? They seem a bit short to me (especially if the maintainer is on vacation -- for this project it is only me at the moment).

2023-05-31 21:48 UTC, Neilblaze commented on .github/workflows/ISSUE_TEMPLATE/config.yaml
@tkuhrt Thank you so much for the feedback. This means that we need to rename every `.yaml` filetype to `.yml`, correct?

If yes, then I'm on it! 🚀

2023-05-31 21:52 UTC, Neilblaze commented on .github/workflows/ISSUE_TEMPLATE/bug-report.yaml
> +labels: [Bug, Needs Triage]
Makes sense! I'll remove `Needs Triage` from the list. That also means that I've to add a `labels.yml` file for convenience, correct? If yes, then can you please suggest me a few labels?

2023-05-31 21:56 UTC, Neilblaze commented on .github/workflows/ISSUE_TEMPLATE/improve_docs.yml
> +        - Search the [open issues](https://github.com/hyperledger-labs/documentation-template/issues) to avoid duplicating the issue.
Sure, I'll update those! :)

2023-05-31 22:10 UTC, Neilblaze commented on .github/workflows/PULL_REQUEST_TEMPLATE.md
@tkuhrt I think _H1_ (`#`) being large, might be a bit too overwhelming for the eyes if we use it throughout the page haha 😂 

It'll be better if we go for either **H2** or **H3** instead of _H4_. 🤔

2023-05-31 22:10 UTC, Neilblaze commented on .github/workflows/PULL_REQUEST_TEMPLATE.md
I'm going forward with H2 for now :)

2023-05-31 22:16 UTC, Neilblaze commented on .github/workflows/stale.yml
We can use the `awaiting response` label here. Keeping a limelight on your point, I think we can extend all three (`daysUntilStale`, `daysUntilClose` & `daysBeforeReminder`) to 30, 60, and 14 days (from 5, 12 & 3).

I believe this should give the reviewer ample time & flexibility to provide their feedback at their own convenience :)

2023-06-01 16:37 UTC, tkuhrt commented on .github/workflows/ISSUE_TEMPLATE/bug-report.yaml
> +labels: [Bug, Needs Triage]
Interesting, I didn't know you could create a `labels.yml` file. I wonder if there is a way to export the [labels that we have now in this repo](https://github.com/hyperledger-labs/documentation-template/labels).

2023-06-01 16:45 UTC, tkuhrt commented on .github/workflows/ISSUE_TEMPLATE/bug-report.yml
> +labels: [Bug]
I am guessing that we need case-sensitivity here. The `bug` label has a lowercase `b`. I am okay to leave the `needs triage` label. We can add that to the list of labels. Just wanted to be sure that I called it out to remind me to do this. Also, the lowercase since all of the labels provided by default are lower case, I want to the consistent.

2023-06-01 16:47 UTC, Neilblaze commented on .github/workflows/ISSUE_TEMPLATE/config.yaml
Yeah, I was also looking into the same. I think sometimes GitHub workflows can come up with some complications, but in general both `.yaml` and `.yml` should function equally well.

2023-06-01 16:50 UTC, tkuhrt commented on .github/workflows/ISSUE_TEMPLATE/bug-report.yml
> +labels: [Bug]
Added the `needs triage` label to the list of available labels in this template.

2023-06-01 17:03 UTC, Neilblaze commented on .github/workflows/ISSUE_TEMPLATE/bug-report.yml
> +labels: [Bug]
Sure, I'll make sure each one of them is consistent & in lowercase :)

2023-06-01 17:07 UTC, Neilblaze commented
> One thing that I was thinking about last night regarding this PR... This repository is intended to be used as a template for people creating documentation for their projects. Thoughts on whether it makes sense to include the issue and PR templates in a template repository? I am leaning towards yes, but wanted to get another perspective since my brain is wondering.

@tkuhrt, you've raised an excellent point here. I actually had a discussion with Bobbi about this during our last community call. The main goal is to empower contributors by allowing them to customize the template according to their specific requirements. This way, we ensure that the template remains dynamic and adaptable, capable of scaling to different needs :)

2023-06-01 19:43 UTC, Neilblaze commented on .github/workflows/ISSUE_TEMPLATE/bug-report.yaml
> +labels: [Bug, Needs Triage]
@tkuhrt I've pushed the requested changes in the most recent [commit](https://github.com/hyperledger-labs/documentation-template/pull/10/commits/61df46217a3daa038a9aa32f115e66f2953343a4). For maintaining transparency, I've used the color codes of these [colors](https://twitter.com/github/status/954467266434945024) for the labels. Besides, I've added two more labels (`awaiting response` and `stale`) in the list of labels.

Do lemme know if any other changes are required :)

2023-06-01 20:15 UTC, merged

2023-06-01 20:18 UTC, tkuhrt commented
@Neilblaze after the merge, I am not seeing the new labels or the issue types show up. Maybe we did need `.yaml` for the other templates. Can you take a look?  I am on my mobile and may not be seeing something.

2023-06-02 05:26 UTC, Neilblaze commented
> after the merge, I am not seeing the new labels or the issue types show up. Maybe we did need `.yaml` for the other templates. Can you take a look? I am on my mobile and may not be seeing something.

@tkuhrt Yes, I did some research & found out that [they](https://github.com/buildpacks/github-actions/blob/main/.github/labels.yml) were using another GitHub Actions workflow to automatically synchronize the labels defined in `labels.yml` with the (default) labels in the repository (which were manually defined). 

**I'd recommend keeping this aside for a while**, till I find some wayarounds. 😅  
Else, we need to follow these steps to create the workflow:

```yml
name: Label Sync

on:
  push:
    branches:
      - main

jobs:
  sync-labels:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Sync labels
        uses: github/label-sync@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          labels-file: .github/labels.yml
```

In this example, the workflow is triggered on each push to the `main` branch. It uses the `github/label-sync` action to synchronize the labels defined in labels.yml with the labels in your repository. The `repo-token` input is set to ${{ secrets.GITHUB_TOKEN }}, which is a built-in secret provided by GitHub Actions. Once the workflow runs, it will automatically update the labels in your repository based on the definitions in the `labels.yml` file.

You can follow [this](https://github.com/Financial-Times/github-label-sync/blob/master/.github/workflows/sync-repo-labels.yml) for reference. This also provides additional benefits like [_auto-applying_](https://github.com/Financial-Times/github-label-sync/blob/master/.github/workflows/apply-labels.yml) labels to issue(s).